version: '3.2'

services:

  mysql:
    image: mysql:8.0.27
    container_name: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - ./db/mysql-data:/var/lib/mysql
      - ./db/mysql-initdb-d:/docker-entrypoint-initdb.d
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
      MYSQL_USER: "mysql"
      MYSQL_PASSWORD: "mysql"
      MYSQL_DATABASE: "todo"
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 10s
      retries: 5

  flyway:
    build:
      context: ./db/flyway
      dockerfile: Dockerfile
    pull_policy: build
    image: todo-app-flyway:latest
    container_name: flyway
    depends_on:
      mysql:
        condition: service_healthy
    command: "-configFiles=/flyway/conf/flyway-dev.conf repair migrate"

  nginx-basic-auth:
    container_name: nginx-basic-auth
    image: beevelop/nginx-basic-auth:v2021.02.1
    ports:
      - "8111:80"
    environment:
      # apr1 hash - $$ (экранирование знака $)
      HTPASSWD: admin:$$apr1$$K3hIHvp9$$CGnOCuffpwYynXXLaB8Fm/
      FORWARD_HOST: adminer
      FORWARD_PORT: 8080
    links:
      - adminer
    depends_on:
      - adminer

  adminer:
    image: adminer:4.8.1-standalone
    container_name: adminer
    restart: always
    environment:
      ADMINER_DESIGN: dracula
      ADMINER_DEFAULT_SERVER: mysql
    depends_on:
      mysql:
        condition: service_healthy

  minio:
    image: minio/minio:RELEASE.2022-01-27T03-53-02Z
    container_name: minio
    #    restart: always
    command: "server /data --console-address ':9001'"
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - ./minio/data:/data
    environment:
      MINIO_ROOT_USER: "minio"
      MINIO_ROOT_PASSWORD: "miniopsw"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9000/minio/health/live" ]
      interval: 10s
      timeout: 10s
      retries: 3

  miniomc:
    image: minio/mc:RELEASE.2022-01-29T01-03-27Z
    container_name: miniomc
    depends_on:
      minio:
        condition: service_healthy
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc config host add myminio http://minio:9000 minio miniopsw;
      /usr/bin/mc mb --ignore-existing myminio/todo-app-bucket;
      exit 0;
      "

  # todo-app:
  #   image: todo-app:latest
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   pull_policy: build
  #   container_name: todo-app
  #   restart: always
  #   environment:
  #     APP_PROFILE_ACTIVE: "PROD"
  #     MINIO_ENDPOINT: "minio:9000"
  #     MINIO_ACCESS_KEY: "minio"
  #     MINIO_SECRET_KEY: "miniopsw"
  #     MY_SQL_DRIVER_NAME: "mysql"
  #     MY_SQL_DATASOURCE_URL: "mysql:mysql@tcp(mysql:3306)/todo?parseTime=true"
  #   ports:
  #     - "8222:8222"
  #   depends_on:
  #     mysql:
  #       condition: service_healthy
  #     minio:
  #       condition: service_healthy