version: '3.2'

services:

  mysql:
    image: mysql:8.0.27
    container_name: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - ./mysql-data:/var/lib/mysql
      - ./mysql-initdb-d:/docker-entrypoint-initdb.d
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
      MYSQL_USER: "mysql"
      MYSQL_PASSWORD: "mysql"
      MYSQL_DATABASE: "todo"
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 10s
      retries: 5

  flyway:
    image: todo-app-flyway:latest
    container_name: flyway
    depends_on:
      mysql:
        condition: service_healthy
    command: "-configFiles=/flyway/conf/flyway-dev.conf repair migrate"

  nginx-basic-auth:
    container_name: nginx-basic-auth
    image: beevelop/nginx-basic-auth:v2021.02.1
    ports:
      - "8111:80"
    environment:
      # apr1 hash - $$ (экранирование знака $)
      HTPASSWD: admin:$$apr1$$K3hIHvp9$$CGnOCuffpwYynXXLaB8Fm/
      FORWARD_HOST: adminer
      FORWARD_PORT: 8080
    links:
      - adminer
    depends_on:
      - adminer

  adminer:
    image: adminer:4.8.1-standalone
    container_name: adminer
    restart: always
    environment:
      ADMINER_DESIGN: dracula
      ADMINER_DEFAULT_SERVER: mysql
    depends_on:
      mysql:
        condition: service_healthy
