version: '3.2'

services:

  minio:
    image: minio/minio:RELEASE.2022-01-27T03-53-02Z
    container_name: minio
#    restart: always
    command: "server /data --console-address ':9001'"
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - ./data:/data
    environment:
      MINIO_ROOT_USER: "minio"
      MINIO_ROOT_PASSWORD: "miniopsw"
